### ISSUE TITLE
Add No License (private projects)

### ISSUE THREAD

**Issue by AkdM** [nikitavoloboev/license-up#11]

**Comment by jletey** [comment]
I've never seen this license before ... could you please give me an example and I'd be happy to implement it!

**Comment by jletey** [comment]
Do you mean [Unlicense](https://oss.ninja/unlicense)?

**Comment by nikivdev** [comment]
> Unlicense

I am pretty sure he meant that. That's the only license that legalizes `No License` statement I know. Let's add it.

**Comment by jletey** [comment]
Sounds good! Getting on it right now!
