### ISSUE TITLE
List of Licenses to Add

### ISSUE THREAD

**Issue by jletey** [nikitavoloboev/license-up#18]
Below is a list of popular licenses that we should think about adding (taken from [opensource.org](https://opensource.org/licenses)):

- [ ] [Apache License 2.0](https://opensource.org/licenses/Apache-2.0)
- [ ] GNU General Public License (GPL)
   - [ ] [GNU General Public License version 2](https://opensource.org/licenses/GPL-2.0)
   - [ ] [GNU General Public License version 3](https://opensource.org/licenses/GPL-3.0)
- [ ] GNU Library or "Lesser" General Public License (LGPL)
   - [ ] [GNU Library General Public License, version 2](https://opensource.org/licenses/LGPL-2.0)
   - [ ] [GNU Library General Public License, version 2.1](https://opensource.org/licenses/LGPL-2.1)
   - [ ] [GNU Library General Public License, version 3](https://opensource.org/licenses/LGPL-3.0)
- [ ] [Mozilla Public License 2.0](https://opensource.org/licenses/MPL-2.0)
- [ ] [Common Development and Distribution License](https://opensource.org/licenses/CDDL-1.0)
- [ ] [Eclipse Public License](https://opensource.org/licenses/EPL-1.0)

Plus the ones that have already been requested in issues (@AkdM)

- [ ] WTFPL (#12)
- [x] Unlicense (#11)

*Please feel free to add any licenses that you would like to include*
*I'll try to keep this up to date*

**Comment by jletey** [comment]
@nikitavoloboev What are your thoughts on this ... we definitely still need to add WTFPL and the GPL licenses ... but I'm not quite sure about the others

**Comment by nikivdev** [comment]
I agree. I would add the most used licenses and for the rest make contribution easier by doing #19 and good contributing.md file so anyone else can add a license they like.

**Comment by jletey** [comment]
Sounds good ... I've already added GPLv3 (#22) ... let's add GPLv2 and WTFPL, and then get started on #19.
