### ISSUE TITLE
If `LICENSE` file is already present, mention it

### ISSUE THREAD

**Issue by nikivdev** [nikitavoloboev/license-up#23]
Right now it will just overwrite the existing LICENSE with the new one. I think a better behavior is to say:

`There is already a license present in current directory. Do you want to overwrite it with a new one? Y/N`

**Comment by nikitavoloboev** [comment]
Although on the other hand it would be nice to not have to go through this prompt. Perhaps have a `-f` flag you can pass to get the same behavior as we have now.

**Comment by jletey** [comment]
I like this a lot

I'll start looking into how to do this (should just be a simple `if` statement when we parse the input in `main.go`)
