### ISSUE TITLE
Testing Locally

### ISSUE THREAD

**Issue by jletey** [nikitavoloboev/license-up#27]
Hey Nikita,

When I've been making PRs, I haven't been testing the code locally, since I don't know how

I tried `go get ./...`, but I get an error message saying:

```
go get: no install location for directory /Users/john/license-up outside GOPATH
	For more details see: 'go help gopath'
```

How to you test locally? This is probably good to add to `CONTRIBUTING.md`

**Comment by nikivdev** [comment]
For me the code is inside my GOPATH so:

`~/go/src/github.com/nikitavoloboev/license-up`

For you, I believe you should clone it to:

`~/go/src/github.com/johnletey/license-up`

And from there you can run `go install`. This should put the tool in your PATH to use. 

[How to write Go Code](https://golang.org/doc/code.html) has more info. One thing we can do for future is move to [Go Modules](https://github.com/golang/go/wiki/Modules). This removes the GOPATH issue.

**Comment by jletey** [comment]
Ah ... thanks

I had the code in `~/license-up` ... I'll move it

I'll add this to the contributing guide
