### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by michaelmior** [nikitavoloboev/license-up#34]
Would be great if there was an option to instead generate `LICENSE.md` with the license in Markdown format.

**Comment by nikivdev** [comment]
Sure. I think we can add a flag for that. For example `license-up -md mit` would create `LICENSE.md` with MIT license.

cc @johnletey

**Comment by jletey** [comment]
This is definitely a possibility ... I'll start looking into it!

It would probably be `license-up --md mit`
